"""v1 initial schema — full data model

Revision ID: 7b3865da33ce
Revises: 
Create Date: 2026-08-24 15:31:46.706990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3865da33ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('faction', sa.String(length=20), nullable=False),
    sa.Column('discord_guild_id', sa.String(length=50), nullable=False),
    sa.Column('discord_member_role_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_guild_id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('faction', sa.String(length=20), nullable=False),
    sa.Column('crate_size', sa.Integer(), nullable=False),
    sa.Column('produced_at', sa.String(length=50), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.CheckConstraint('crate_size > 0', name='ck_items_crate_size_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('discord_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('access_token', sa.String(length=500), nullable=True),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_discord_id'), ['discord_id'], unique=True)

    op.create_table('vehicle_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('faction', sa.String(length=20), nullable=False),
    sa.Column('produced_at', sa.String(length=50), nullable=False),
    sa.Column('cargo_slots', sa.Integer(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('wars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('wars', schema=None) as batch_op:
        batch_op.create_index('ix_wars_is_current_unique', ['is_current'], unique=True, postgresql_where=sa.text('is_current = true'))

    op.create_table('audit_logs',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_user', ['user_id', 'created_at'], unique=False)

    op.create_table('group_memberships',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_memberships', schema=None) as batch_op:
        batch_op.create_index('ix_group_memberships_group_status', ['group_id', 'status'], unique=False)
        batch_op.create_index('ix_group_memberships_group_user', ['group_id', 'user_id'], unique=True)

    op.create_table('regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('war_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hex_code', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['war_id'], ['wars.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regions_war_id'), ['war_id'], unique=False)
        batch_op.create_index('ix_regions_war_name', ['war_id', 'name'], unique=True)

    op.create_table('operations',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('war_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('location_detail', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['war_id'], ['wars.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.create_index('ix_operations_group_scheduled', ['group_id', 'scheduled_at'], unique=False)
        batch_op.create_index('ix_operations_status', ['status'], unique=False)

    op.create_table('stockpiles',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('war_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('structure_type', sa.String(length=30), nullable=False),
    sa.Column('code_6digit', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['war_id'], ['wars.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stockpiles', schema=None) as batch_op:
        batch_op.create_index('ix_stockpiles_group_war', ['group_id', 'war_id'], unique=False)

    op.create_table('logistics_orders',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_stockpile_id', sa.String(length=36), nullable=True),
    sa.Column('destination_stockpile_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['destination_stockpile_id'], ['stockpiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_stockpile_id'], ['stockpiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logistics_orders', schema=None) as batch_op:
        batch_op.create_index('ix_logistics_orders_group_status', ['group_id', 'status'], unique=False)
        batch_op.create_index('ix_logistics_orders_operation', ['operation_id'], unique=False)

    op.create_table('operation_signups',
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('requested_role', sa.String(length=100), nullable=True),
    sa.Column('confirmed_role', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('signed_up_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_signups', schema=None) as batch_op:
        batch_op.create_index('ix_operation_signups_op_user', ['operation_id', 'user_id'], unique=True)

    op.create_table('resource_requests',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_crates', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity_crates > 0', name='ck_resource_requests_qty_positive'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['logistics_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_requests_order_id'), ['order_id'], unique=False)

    op.create_table('transport_runs',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=True),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=False),
    sa.Column('origin_stockpile_id', sa.String(length=36), nullable=False),
    sa.Column('destination_stockpile_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_stockpile_id'], ['stockpiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['logistics_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_stockpile_id'], ['stockpiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transport_runs', schema=None) as batch_op:
        batch_op.create_index('ix_transport_runs_driver_status', ['driver_id', 'status'], unique=False)
        batch_op.create_index('ix_transport_runs_order_status', ['order_id', 'status'], unique=False)

    op.create_table('vehicle_requests',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_vehicle_requests_qty_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['logistics_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_requests_order_id'), ['order_id'], unique=False)

    op.create_table('production_tasks',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('resource_request_id', sa.String(length=36), nullable=True),
    sa.Column('vehicle_request_id', sa.String(length=36), nullable=True),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('facility_stockpile_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(resource_request_id IS NOT NULL AND vehicle_request_id IS NULL) OR (resource_request_id IS NULL AND vehicle_request_id IS NOT NULL)', name='ck_production_tasks_one_target'),
    sa.CheckConstraint('quantity > 0', name='ck_production_tasks_qty_positive'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['facility_stockpile_id'], ['stockpiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['logistics_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_request_id'], ['resource_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_request_id'], ['vehicle_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_production_tasks_assignee_status', ['assignee_id', 'status'], unique=False)
        batch_op.create_index('ix_production_tasks_order_status', ['order_id', 'status'], unique=False)

    op.create_table('transport_cargo',
    sa.Column('transport_run_id', sa.String(length=36), nullable=False),
    sa.Column('resource_request_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_crates', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity_crates > 0', name='ck_transport_cargo_qty_positive'),
    sa.ForeignKeyConstraint(['resource_request_id'], ['resource_requests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transport_run_id'], ['transport_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transport_cargo', schema=None) as batch_op:
        batch_op.create_index('ix_transport_cargo_run_request', ['transport_run_id', 'resource_request_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_cargo', schema=None) as batch_op:
        batch_op.drop_index('ix_transport_cargo_run_request')

    op.drop_table('transport_cargo')
    with op.batch_alter_table('production_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_production_tasks_order_status')
        batch_op.drop_index('ix_production_tasks_assignee_status')

    op.drop_table('production_tasks')
    with op.batch_alter_table('vehicle_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_requests_order_id'))

    op.drop_table('vehicle_requests')
    with op.batch_alter_table('transport_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_transport_runs_order_status')
        batch_op.drop_index('ix_transport_runs_driver_status')

    op.drop_table('transport_runs')
    with op.batch_alter_table('resource_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_requests_order_id'))

    op.drop_table('resource_requests')
    with op.batch_alter_table('operation_signups', schema=None) as batch_op:
        batch_op.drop_index('ix_operation_signups_op_user')

    op.drop_table('operation_signups')
    with op.batch_alter_table('logistics_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_logistics_orders_operation')
        batch_op.drop_index('ix_logistics_orders_group_status')

    op.drop_table('logistics_orders')
    with op.batch_alter_table('stockpiles', schema=None) as batch_op:
        batch_op.drop_index('ix_stockpiles_group_war')

    op.drop_table('stockpiles')
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_index('ix_operations_status')
        batch_op.drop_index('ix_operations_group_scheduled')

    op.drop_table('operations')
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_index('ix_regions_war_name')
        batch_op.drop_index(batch_op.f('ix_regions_war_id'))

    op.drop_table('regions')
    with op.batch_alter_table('group_memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_group_memberships_group_user')
        batch_op.drop_index('ix_group_memberships_group_status')

    op.drop_table('group_memberships')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_user')
        batch_op.drop_index('ix_audit_logs_entity')

    op.drop_table('audit_logs')
    with op.batch_alter_table('wars', schema=None) as batch_op:
        batch_op.drop_index('ix_wars_is_current_unique', postgresql_where=sa.text('is_current = true'))

    op.drop_table('wars')
    op.drop_table('vehicle_types')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_discord_id'))

    op.drop_table('users')
    op.drop_table('items')
    op.drop_table('groups')
    # ### end Alembic commands ###
